// <auto-generated />
using System;
using Erp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ErpDbContext))]
    partial class ErpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Erp.Domain.Bom.BomLine", b =>
                {
                    b.Property<string>("ParentItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BomVersion")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QtyPer")
                        .HasColumnType("TEXT");

                    b.HasKey("ParentItemCode", "ComponentItemCode", "BomVersion");

                    b.HasIndex("ParentItemCode");

                    b.ToTable("bom_lines", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Inventory.InventoryBalance", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OnHandQty")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReservedQty")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemCode");

                    b.ToTable("inventory_balances", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Items.Item", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemCode");

                    b.HasIndex("ItemName");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Items.ItemSupplyInfo", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinOrderQty")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrderMultiple")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemCode");

                    b.ToTable("item_supply_infos", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Production.RoutingStep", b =>
                {
                    b.Property<string>("WorkOrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepNo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CompletedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlannedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkOrderNo", "StepNo");

                    b.ToTable("routing_steps", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Production.WorkOrder", b =>
                {
                    b.Property<string>("WorkOrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialIssueStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlannedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkOrderNo");

                    b.HasIndex("Status", "DueDate");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Purchasing.PurchaseOrder", b =>
                {
                    b.Property<string>("PoNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpectedArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReceivedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PoNo");

                    b.HasIndex("ItemCode", "Status");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("Erp.Domain.Quality.QualityInspection", b =>
                {
                    b.Property<string>("InspectionNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InspectedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InspectedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PassedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkOrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("InspectionNo");

                    b.HasIndex("WorkOrderNo");

                    b.HasIndex("ItemCode", "InspectedAt");

                    b.ToTable("quality_inspections", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
